(() => {
  "use strict";
  document.documentElement.lang = "en";

  const phrases = [
    ["A Copa do Mundo como você nunca viu, em tempo real", "The World Cup as you've never seen it, live"],
    ["Tabela de pontos atualizada minuto a minuto, condições de jogo ao vivo e reprodução dos lances mais incríveis. Tudo em um só lugar.", "Minute-by-minute standings, live match conditions, and replays of the most incredible plays. All in one place."],
    ["Acompanhe a tabela de pontos em tempo real, o placar ao vivo de cada partida e reveja os melhores momentos — tudo em um só lugar.", "Follow real-time standings and every live score, then relive the best moments — all in one place."],
    ["O painel chega povoado e nunca para: cada número se refaz caractere por caractere, e só a linha que mudou se move. Filtre, ordene, inclua ou remova — o fluxo continua.", "The board arrives populated and never stops: every number flips character by character, and only the changed row moves. Filter, sort, add, or remove — the flow continues."],
    ["A direção aparece duas vezes por linha: na forma, antes dos dígitos, e no selo colorido depois deles.", "Direction appears twice on every row: as a shape before the digits and as a colored badge after them."],
    ["placar, minuto e dados com a mesma mecânica de dígitos — se o dado atrasa, o valor anterior permanece", "score, match time, and data use the same digit mechanism — if data is delayed, the previous value remains"],
    ["Clique nos cabeçalhos para ordenar. As posições reagem aos gols marcados ao vivo.", "Click the headers to sort. Positions respond to goals scored live."],
    ["Cadastre-se gratuitamente para acompanhar seus times, receber alertas de gol em tempo real e concorrer a uma camisa oficial autografada.", "Sign up free to follow your teams, receive real-time goal alerts, and enter to win a signed official jersey."],
    ["Placar, posse de bola, finalizações e o minuto a minuto de cada batalha em campo.", "Score, possession, shots, and a minute-by-minute view of every battle on the pitch."],
    ["Reveja os melhores momentos, gols e defesas espetaculares da competição.", "Relive the tournament's best moments, goals, and spectacular saves."],
    ["Placares e cronômetros atualizados automaticamente durante os jogos.", "Scores and clocks update automatically during matches."],
    ["Gols, defesas e lances decisivos — reveja em segundos.", "Goals, saves, and decisive plays — relive them in seconds."],
    ["Acompanhe os principais lances desta partida.", "Follow the key moments from this match."],
    ["Central ao vivo da Copa do Mundo 2026: tabela de pontos em tempo real, condições de jogo ao vivo, lances em vídeo e replay quadro a quadro.", "World Cup 2026 live center: real-time standings, live match conditions, video highlights, and frame-by-frame replay."],
    ["A ABERTURA SE FECHA NOS DOIS EXTREMOS DO TRECHO", "THE OPENING CLOSES AT BOTH ENDS OF THE SEQUENCE"],
    ["GOL AOS 78' — FINALIZACAO DE PRIMEIRA", "GOAL AT 78' — FIRST-TIME FINISH"],
    ["CRUZAMENTO RASTEIRO NO SEGUNDO PAU", "LOW CROSS TO THE FAR POST"],
    ["INVERSAO LONGA EM DOIS TOQUES", "LONG SWITCH IN TWO TOUCHES"],
    ["TABELINHA DE PRIMEIRA NO CORREDOR", "ONE-TOUCH COMBINATION DOWN THE CHANNEL"],
    ["ROUBADA DE BOLA NA INTERMEDIARIA", "BALL WON IN MIDFIELD"],
    ["SEM AVANCO AUTOMATICO", "NO AUTOPLAY"],
    ["ROLE PARA REPRODUZIR", "SCROLL TO PLAY"],
    ["A emoção da Copa,", "The thrill of the World Cup,"],
    ["minuto a minuto", "minute by minute"],
    ["TRANSMISSÃO AO VIVO AGORA", "LIVE BROADCAST NOW"],
    ["Tabela de Pontos em Tempo Real", "Real-Time Standings"],
    ["Pontuação atualizada automaticamente conforme os jogos acontecem.", "Points update automatically as matches unfold."],
    ["Condições de Jogo em Tempo Real", "Real-Time Match Conditions"],
    ["Reprodução dos Lances Maravilhosos", "Spectacular Play Replays"],
    ["Palpite e Concorra a Prêmios", "Make Your Pick and Win Prizes"],
    ["Classificado para as oitavas de final", "Qualified for the round of 16"],
    ["Pular para a tabela de classificação", "Skip to the standings table"],
    ["Contagem regressiva para a próxima grande partida", "Countdown to the next big match"],
    ["Contagem regressiva para o apito inicial", "Countdown to kickoff"],
    ["Temporada 2026 · Fase de Grupos", "2026 Season · Group Stage"],
    ["Situação em tempo real", "Real-time status"],
    ["Classificação em tempo real", "Real-time standings"],
    ["Atualizado em tempo real. Ordenação padrão por pontos.", "Updated in real time. Default sorting by points."],
    ["Próxima grande partida", "Next big match"],
    ["Final · Brasil × França", "Final · Brazil × France"],
    ["Classificado (1º–2º)", "Qualified (1st–2nd)"],
    ["Repescagem (3º)", "Playoff (3rd)"],
    ["V vitória · E empate · D derrota", "W win · D draw · L loss"],
    ["Tabela de pontos em tempo real", "Real-time standings"],
    ["Tabela de pontos", "Standings"],
    ["Partidas ao vivo", "Live matches"],
    ["Melhores Momentos", "Highlights"], ["Melhores momentos", "Highlights"],
    ["Reprodução maravilhosa", "Spectacular replay"],
    ["Promoção Oficial", "Official Giveaway"], ["Participar Grátis", "Join for Free"],
    ["Entrar na Promoção", "Enter the Giveaway"], ["Quero Participar", "I Want to Join"],
    ["Ver Jogos Ao Vivo", "Watch Live Matches"], ["Assistir agora", "Watch now"],
    ["Ver classificação", "View standings"], ["Ver todos os melhores momentos", "View all highlights"],
    ["Ver tudo", "View all"], ["Detalhes da partida", "Match details"],
    ["AO VIVO / CONDIÇÕES DE GUERRA", "LIVE / MATCH CONDITIONS"],
    ["Placar & Estatísticas", "Score & Statistics"], ["TABELA DE PONTOS", "STANDINGS"],
    ["MELHORES MOMENTOS", "HIGHLIGHTS"], ["FINAL · Grupo de Elite", "FINAL · Elite Group"],
    ["Grupo A · Estádio Central", "Group A · Central Stadium"],
    ["Pular para o conteúdo", "Skip to content"], ["Navegação principal", "Main navigation"],
    ["Abrir menu", "Open menu"], ["Fechar reprodução", "Close replay"],
    ["Reproduzindo lance...", "Playing highlight..."], ["Atualizando…", "Updating…"],
    ["3 jogos ao vivo", "3 live matches"],
    ["48 seleções · 16 sedes · 104 partidas", "48 teams · 16 host cities · 104 matches"],
    ["↓ próximo lance · ↑ lance anterior", "↓ next highlight · ↑ previous highlight"],
    ["sem som · clique no véu ou em ✕ para fechar", "muted · click the overlay or ✕ to close"],
    ["03 — painel mecânico", "03 — mechanical board"],
    ["fluxo contínuo · sem parada", "continuous flow · no pauses"],
    ["Filtrar seleções", "Filter teams"], ["Filtrar sigla ou seleção", "Filter code or team"],
    ["Adicionar sigla", "Add team code"], ["linhas em exibição", "rows displayed"],
    ["Direção da variação", "Change direction"], ["Painel vazio.", "Empty board."],
    ["Adicione uma sigla", "Add a team code"], ["no campo acima para começar.", "in the field above to begin."],
    ["Nenhuma linha corresponde a", "No rows match"], ["Maiores variações", "Largest changes"],
    ["mesmo conjunto", "same dataset"], ["Aguardando a primeira variação do painel.", "Waiting for the board's first change."],
    ["Como ler o painel", "How to read the board"], ["triângulo cheio para cima", "solid upward triangle"],
    ["a seleção subiu", "the team moved up"], ["triângulo cheio para baixo", "solid downward triangle"],
    ["a seleção caiu", "the team moved down"], ["traço neutro — linha em repouso", "neutral dash — unchanged row"],
    ["Condições de jogo agora", "Match conditions now"], ["Condições de jogo", "Match conditions"],
    ["painel mecânico", "mechanical board"], ["Remover", "Remove"], ["do painel", "from the board"],
    ["em alta", "rising"], ["em queda", "falling"], ["estável", "stable"],
    ["sinal instável · último dado", "unstable signal · last data"], ["atualizado", "updated"],
    ["tendência", "trend"], ["Seleção", "Team"], ["Seleções", "Teams"],
    ["Partidas", "Matches"], ["Gols", "Goals"], ["Jogos", "Played"],
    ["Vitórias", "Wins"], ["Empates", "Draws"], ["Derrotas", "Losses"],
    ["Últimos 5", "Last 5"], ["Forma", "Form"], ["Classificação", "Standings"],
    ["Tabela", "Standings"], ["Ao Vivo", "Live"], ["AO VIVO", "LIVE"], ["ao vivo", "live"],
    ["Lances", "Highlights"], ["Promoção", "Giveaway"], ["Contagem", "Countdown"],
    ["Vídeo", "Video"], ["Dias", "Days"], ["Horas", "Hours"], ["Seg", "Sec"],
    ["Posse de bola", "Possession"], ["Posse", "Possession"], ["Finalizações", "Shots"],
    ["Grupo", "Group"], ["Encerrado", "Finished"], ["Aguardando início da partida.", "Waiting for kickoff."],
    ["Hoje", "Today"], ["Detalhes", "Details"], ["Reprise", "Replay"],
    ["Programada", "Scheduled"], ["Resultado final", "Final score"], ["Ao vivo agora", "Live now"],
    ["vitória", "win"], ["empate", "draw"], ["derrota", "loss"],
    ["Golaço", "Wonder goal"], ["Defesa", "Save"], ["Gol", "Goal"], ["Pênalti", "Penalty"],
    ["duração", "duration"], ["contra", "versus"],
    ["Brasil", "Brazil"], ["França", "France"], ["Croácia", "Croatia"], ["Suíça", "Switzerland"],
    ["Camarões", "Cameroon"], ["Holanda", "Netherlands"], ["Países Baixos", "Netherlands"],
    ["Alemanha", "Germany"], ["Espanha", "Spain"], ["Inglaterra", "England"],
    ["Uruguai", "Uruguay"], ["Gana", "Ghana"], ["Japão", "Japan"], ["Marrocos", "Morocco"],
    ["México", "Mexico"], ["Canadá", "Canada"], ["Colômbia", "Colombia"], ["Bélgica", "Belgium"],
    ["Itália", "Italy"], ["Dinamarca", "Denmark"], ["Coreia do Sul", "South Korea"],
    ["Austrália", "Australia"], ["Equador", "Ecuador"], ["Sérvia", "Serbia"], ["Noruega", "Norway"],
    ["Egito", "Egypt"], ["Nigéria", "Nigeria"], ["Paraguai", "Paraguay"], ["Estados Unidos", "United States"],
    ["Copa do Mundo", "World Cup"], ["Copa Mundial", "World Cup"],
    ["Central Ao Vivo", "Live Center"], ["Central ao Vivo", "Live Center"], ["Central ao vivo", "Live Center"],
    ["como você nunca viu, em tempo real", "as you've never seen it, live"],
    ["Estádio Maracanã", "Maracanã Stadium"], ["Estádio Nacional", "National Stadium"],
    ["Estádio Beira-Rio", "Beira-Rio Stadium"], ["Estádio Azteca", "Azteca Stadium"],
    ["Estádio", "Stadium"], ["PLACAR", "SCORE"], ["No alvo", "On target"],
    ["Gol de", "Goal by"], ["Cartão amarelo", "Yellow card"], ["Fim de jogo", "Full time"],
    ["Golaço de bicicleta — Brasil x Argentina", "Bicycle-kick wonder goal — Brazil vs Argentina"],
    ["Defesa milagrosa aos 89'", "Miraculous save in the 89th minute"],
    ["Drible desconcertante no meio", "Dazzling dribble through midfield"],
    ["Cobrança de falta indefensável", "Unstoppable free kick"],
    ["Contra-ataque relâmpago", "Lightning counterattack"],
    ["Pintura de fora da área", "Stunning strike from outside the box"],
    ["Vinícius Júnior emenda de primeira num voleio perfeito no ângulo.", "Vinícius Júnior meets it first time with a perfect volley into the top corner."],
    ["O goleiro voa no canto e garante os três pontos no último lance.", "The goalkeeper flies into the corner and secures all three points on the final play."],
    ["Sequência de fintas que deixa dois marcadores no chão.", "A sequence of feints leaves two defenders on the ground."],
    ["A bola faz uma curva impossível por cima da barreira.", "The ball curls impossibly over the wall."],
    ["Da defesa ao ataque em oito segundos e finalização precisa.", "From defense to attack in eight seconds, finished with precision."],
    ["Chute colocado de trivela que morre na gaveta.", "An outside-of-the-foot strike nestles in the top corner."],
    ["Dados demonstrativos", "Demonstration data"], ["Eliminado", "Eliminated"],
    ["Voleio de Neymar de fora da área", "Neymar volley from outside the box"],
    ["Milagre do goleiro no último minuto", "Goalkeeper miracle in the final minute"],
    ["Cobrança de falta perfeita", "Perfect free kick"],
    ["Passe de calcanhar genial", "Brilliant backheel pass"],
    ["Contra-ataque em 8 segundos", "Counterattack in 8 seconds"],
    ["Cavadinha decisiva na disputa", "Decisive chipped penalty in the shootout"],
    ["Central de acompanhamento em tempo real", "Real-time match center"],
    ["Copa", "World Cup"],
    ["LANCE EM DESTAQUE · BRA 1 X 0 SUI · CAMERA 12", "FEATURED PLAY · BRA 1–0 SUI · CAMERA 12"],
    ["ROLAGEM = TEMPO", "SCROLL = TIME"], ["AVANCANDO", "FORWARD"],
    ["RETROCEDENDO", "REWINDING"], ["CONGELADO", "PAUSED"],
    ["QUADRO", "FRAME"], ["QPS", "FPS"], ["GOL", "GOAL"], ["DEFESA", "SAVE"],
    ["central ao vivo", "live center"], ["lances", "highlights"], ["tabela", "standings"],
    ["quadro a quadro", "frame by frame"], ["LANCES", "HIGHLIGHTS"], ["TABELA", "STANDINGS"],
    ["QUADRO A QUADRO", "FRAME BY FRAME"], ["Câmera aérea", "Aerial camera"],
    ["PRÉ-JOGO", "PRE-MATCH"], ["Cerimônia de abertura", "Opening ceremony"],
    ["Entrada das seleções", "Teams enter the pitch"], ["sem som", "muted"], ["SEM SOM", "MUTED"],
    ["Voleio no ângulo", "Volley into the top corner"], ["Defesa impossível", "Impossible save"],
    ["Falta por cima da barreira", "Free kick over the wall"], ["Bola parada", "Set piece"],
    ["A arquibancada canta", "The stands erupt in song"], ["INTERVALO", "HALF-TIME"],
    ["Torcida", "Supporters"], ["Arena em festa", "Stadium celebration"], ["PÓS-JOGO", "POST-MATCH"],
    ["Show de luzes", "Light show"], ["Aérea", "Aerial"], ["01 — abertura", "01 — opening"],
    ["role para ver os lances", "scroll to view highlights"], ["02 — lances", "02 — highlights"],
    ["Reprodução maravilhosa", "Spectacular replay"], ["a rolagem move a fileira", "scrolling moves the reel"],
    ["reproduzindo", "playing"], ["Reprodução:", "Replay:"], ["Abrir", "Open"],
    ["HOJE", "TODAY"], ["AMANHÃ", "TOMORROW"], ["SEDE", "HOST CITY"], ["RECORDE", "RECORD"],
    ["Cidade do México", "Mexico City"], ["Nova Jersey", "New Jersey"],
    ["2.240 m de altitude", "2,240 m elevation"], ["104.213 torcedores no Rose Bowl", "104,213 fans at the Rose Bowl"],
    ["gramado híbrido", "hybrid pitch"], ["gol mais rápido", "fastest goal"],
    ["teto retrátil", "retractable roof"], ["umidade", "humidity"], ["vento", "wind"],
    ["41 gols na primeira semana", "41 goals in the first week"], ["em tempo real", "in real time"],
    ["incluir", "add"], ["INCLUIR", "ADD"], ["Pos", "Pos"], ["Sigla", "Code"], ["SIGLA", "CODE"],
    ["linhas", "rows"], ["em exibição", "displayed"], ["Var", "Change"],
    ["agora", "now"], ["AGORA", "NOW"], ["2ª fase", "Round of 16"], ["MINUTO", "MINUTE"],
    ["POSSE", "POSSESSION"], ["CHUTES", "SHOTS"], ["reproduzindo ·", "playing ·"],
    ["05 — fechamento", "05 — closing"], ["A bola volta ao centro", "The ball returns to the center spot"],
    ["O painel continua rodando enquanto você estiver aqui. Nada termina, nada zera — a próxima atualização já está a caminho.", "The board keeps running while you're here. Nothing ends or resets — the next update is already on its way."],
    ["Onde assistir hoje", "Where to watch today"], ["Escalação do dia no seu e-mail", "Today's lineup in your inbox"],
    ["Um aviso por rodada, com os lances que valem revisão quadro a quadro.", "One update per round, featuring the plays worth reviewing frame by frame."],
    ["Seu e-mail", "Your email"], ["quero receber", "subscribe"],
    ["Pronto. Chega antes do apito inicial.", "Done. It will arrive before kickoff."],
    ["abertura", "opening"], ["fechamento", "closing"],
    ["Peça promocional fictícia · dados simulados · imagens geradas por IA", "Fictional promotional piece · simulated data · AI-generated images"],
    ["3 hat-tricks em 48 h", "3 hat-tricks in 48 h"],
    ["minuto", "minute"], ["posse", "possession"], ["chutes", "shots"],
    ["A bola volta", "The ball returns"], ["ao centro", "to the center spot"],
    ["Por favor, informe seu nome.", "Please enter your name."], ["Informe um e-mail válido.", "Enter a valid email address."],
    ["Você está participando da promoção.", "You're entered in the giveaway."],
    ["Principais lances de", "Key moments from"],
    ["Gol! Neymar abre o placar de cabeça.", "Goal! Neymar opens the scoring with a header."],
    ["Cartão amarelo para De Paul.", "Yellow card for De Paul."],
    ["Empate da Argentina em jogada de escanteio.", "Argentina equalize from a corner."],
    ["Substituição: entra Vini Jr., sai Rodrygo.", "Substitution: Vini Jr. replaces Rodrygo."],
    ["Gol! Vini Jr. recoloca o Brasil na frente.", "Goal! Vini Jr. puts Brazil back in front."],
    ["Reproduzir:", "Play:"], ["Em breve", "Coming soon"],

    ["Ir direto para o conteúdo", "Skip directly to content"],
    ["Jogo em destaque", "Featured match"],
    ["O que está acontecendo agora", "What's happening now"],
    ["Placar, cronômetro e narração do jogo que decide o Grupo E, mais o estado de todas as outras partidas da rodada. Cada estado tem ícone e texto — dá para ler no escuro, no celular ou sem enxergar cor.", "The score, match clock, and commentary from the Group E decider, plus the status of every other match in the round. Each state uses both an icon and text, so it remains readable in the dark, on mobile, or without relying on color."],
    ["Classificação que reordena a cada gol", "Standings that reorder with every goal"],
    ["Ordene por qualquer coluna, alterne entre a tabela parcial (com os jogos em andamento) e a confirmada, e veja quem sobe ou cai de posição enquanto a bola rola.", "Sort by any column, switch between provisional standings with live matches and confirmed results, and see who rises or falls while play continues."],
    ["Como está o campo de batalha", "The state of the battlefield"],
    ["Clima, gramado, público, VAR e a pressão de cada lado do campo — os fatores que explicam por que o jogo mudou de dono nos últimos minutos.", "Weather, pitch, crowd, VAR, and pressure on each side of the field — the factors explaining why control has shifted in the last few minutes."],
    ["Os lances mais bonitos, em detalhe", "The finest highlights, in detail"],
    ["Galeria de melhores momentos com reprodução tática animada: capítulos, velocidade ajustável, trajetória da bola e a linha do tempo da partida.", "A highlights gallery with animated tactical replay: chapters, adjustable speed, ball trajectory, and the match timeline."],
    ["Palpite, pontue, concorra à final", "Predict, score points, win a trip to the final"],
    ["A promoção usa os mesmos dados desta página: cada gol recalcula seus pontos na hora. Envio gratuito e edição liberada até o apito inicial.", "The giveaway uses the same data as this page: every goal recalculates your points instantly. Entry is free and editable until kickoff."],

    ["3ª rodada · decisão de vagas", "Matchday 3 · qualification deciders"],
    ["A copa inteira", "The entire World Cup"],
    ["Tabela de pontos que reordena a cada gol, condições de jogo minuto a minuto direto do gramado e reprodução tática dos lances mais bonitos da rodada — tudo em uma tela, sem recarregar a página.", "Standings that reorder after every goal, minute-by-minute conditions straight from the pitch, and tactical replays of the round's finest plays — all on one screen, without reloading."],
    ["Ver tabela ao vivo", "View live standings"],
    ["Assistir aos lances", "Watch highlights"],
    ["Jogos ao vivo agora", "Matches live now"],
    ["Gols na 3ª rodada", "Goals on matchday 3"],
    ["Lances em reprodução", "Highlights available"],
    ["Torcedores no ar", "Fans online"],
    ["Próxima partida", "Next match"],
    ["Próximo jogo", "Next match"],
    ["capacidade", "capacity"],
    ["fuso exibido", "displayed time zone"],
    ["horas", "hours"],

    ["Seções da página", "Page sections"],
    ["Fechar menu de navegação", "Close navigation menu"],
    ["Abrir menu de navegação", "Open navigation menu"],
    ["jogos ao vivo", "live matches"],
    ["Participe", "Enter now"],

    ["Atualização pausada", "Updates paused"],
    ["Atualizações pausadas", "Updates paused"],
    ["Atualizações automáticas pausadas.", "Automatic updates paused."],
    ["Atualizações automáticas retomadas.", "Automatic updates resumed."],
    ["Retomar", "Resume"],
    ["Pausar", "Pause"],
    ["Sincronizar agora", "Sync now"],
    ["Sincronizando", "Syncing"],
    ["Última sincronização", "Last synced"],
    ["Agora", "Now"],
    ["Partida", "Match"],
    ["Finalização", "Shot"],
    ["Escanteio", "Corner"],
    ["Falta", "Foul"],
    ["Início", "Kickoff"],
    ["Amarelo", "Yellow"],
    ["Vermelho", "Red"],
    ["Substituição", "Substitution"],
    ["Intervalo", "Half-time"],
    ["Placar:", "Score:"],
    ["Total de chutes, incluindo bloqueados e para fora.", "Total shots, including blocked and off-target attempts."],
    ["Chutes que exigiram defesa do goleiro ou entraram.", "Shots that forced a save or went in."],
    ["Gols esperados: soma da probabilidade de gol de cada finalização.", "Expected goals: the combined scoring probability of every shot."],
    ["Escanteios cobrados até agora.", "Corners taken so far."],
    ["Cartões", "Cards"],
    ["Ocultar detalhes", "Hide details"],
    ["Ver gols e estatísticas", "View goals and statistics"],

    ["Gramado rápido", "Fast pitch"],
    ["Bola desliza, favorece o toque curto", "The ball travels quickly, favoring short passing"],
    ["Aderência boa", "Good grip"],
    ["Condição neutra para os dois lados", "Neutral conditions for both teams"],
    ["Gramado úmido", "Damp pitch"],
    ["Risco de escorregões e passes longos imprecisos", "Risk of slipping and inaccurate long passes"],
    ["Guerra total", "All-out battle"],
    ["Muito intenso", "Very intense"],
    ["Intenso", "Intense"],
    ["Controlado", "Controlled"],
    ["Sem revisão", "No review"],
    ["VAR analisando", "VAR checking"],
    ["Decisão confirmada", "Decision confirmed"],
    ["Condições do gramado", "Pitch conditions"],
    ["Temperatura", "Temperature"],
    ["Umidade", "Humidity"],
    ["Vento", "Wind"],
    ["Gramado", "Pitch"],
    ["Piso", "Surface"],
    ["Ruído", "Noise"],
    ["Pico", "Peak"],
    ["Ocupação", "Occupancy"],
    ["Temperatura do jogo", "Match temperature"],
    ["Duelos ganhos", "Duels won"],
    ["Faltas cometidas", "Fouls committed"],
    ["Temperatura do ar medida na borda do campo. Sensação térmica considera umidade e vento.", "Air temperature measured at pitchside. Feels-like temperature accounts for humidity and wind."],
    ["Umidade relativa do ar. Acima de 75% aumenta a fadiga e o número de substituições.", "Relative humidity. Above 75%, fatigue and substitutions tend to increase."],
    ["Velocidade e direção do vento a 2 m do gramado. Afeta cruzamentos e cobranças de falta.", "Wind speed and direction two meters above the pitch. It affects crosses and free kicks."],
    ["Temperatura da superfície do gramado, medida por sensores em seis pontos do campo.", "Pitch-surface temperature measured by sensors at six locations."],
    ["Pressão sonora média da arquibancada nos últimos 30 segundos.", "Average crowd sound pressure over the last 30 seconds."],

    ["Mais vistos", "Most viewed"],
    ["Mais recentes", "Most recent"],
    ["Filtrar lances por tipo", "Filter highlights by type"],
    ["Ordenação dos lances", "Highlight sorting"],
    ["Defesas", "Saves"],
    ["Dribles", "Dribbles"],
    ["Passes", "Passes"],
    ["Contra-ataques", "Counterattacks"],
    ["Contra-ataque", "Counterattack"],
    ["Passe", "Pass"],
    ["Drible", "Dribble"],
    ["Pausar reprodução", "Pause replay"],
    ["Reproduzir lance", "Play highlight"],
    ["Reiniciar lance do começo", "Restart highlight from the beginning"],
    ["Progresso da reprodução", "Replay progress"],
    ["Velocidade da reprodução", "Replay speed"],
    ["Próximo lance", "Next highlight"],
    ["Copiar link do lance", "Copy highlight link"],
    ["Link copiado", "Link copied"],
    ["Diagrama tático do lance:", "Tactical play diagram:"],
    ["Prévia do diagrama:", "Diagram preview:"],
    ["Assistir reprodução:", "Watch replay:"],

    ["Escolha o grupo", "Choose a group"],
    ["Modo de exibição da tabela", "Standings display mode"],
    ["Ao vivo (parcial)", "Live (provisional)"],
    ["Confirmada", "Confirmed"],
    ["Geral", "Overall"],
    ["Forma recente", "Recent form"],
    ["Situação na chave", "Group status"],
    ["Gols pró", "Goals for"],
    ["Gols contra", "Goals against"],
    ["Saldo de gols", "Goal difference"],
    ["Pontos: vitória vale 3, empate 1.", "Points: three for a win, one for a draw."],
    ["Partidas disputadas (inclui o jogo em andamento na visão ao vivo).", "Matches played, including the current live match in provisional view."],
    ["Vitórias na fase de grupos.", "Group-stage wins."],
    ["Empates na fase de grupos.", "Group-stage draws."],
    ["Derrotas na fase de grupos.", "Group-stage losses."],
    ["Gols marcados pela seleção.", "Goals scored by the team."],
    ["Gols sofridos pela seleção.", "Goals conceded by the team."],
    ["Saldo de gols: gols pró menos gols contra. Primeiro critério de desempate.", "Goal difference: goals for minus goals against. The first tiebreaker."],
    ["Resultados na ordem cronológica. O último item pontilhado é o jogo em andamento.", "Results in chronological order. The final dotted item is the match in progress."],
    ["Zona de classificação segundo a posição atual: oitavas, repescagem ou eliminado.", "Qualification zone by current position: round of 16, playoff, or eliminated."],
    ["Sem mudança de posição", "No position change"],
    ["Ordenação oficial da chave", "Official group order"],
    ["Inclui 3ª rodada em andamento", "Includes matchday 3 in progress"],
    ["Posição atual na chave. A seta mostra a mudança em relação à tabela confirmada.", "Current group position. The arrow shows movement relative to the confirmed table."],
    ["Classificado às oitavas", "Qualified for the round of 16"],
    ["Repescagem (melhores terceiros)", "Playoff (best third-place teams)"],
    ["Repescagem", "Playoff"],
    ["Oitavas", "Round of 16"],
    ["Situação", "Status"],
    ["Pontos", "Points"],

    ["Promoção oficial da rodada", "Official matchday giveaway"],
    ["Bolão Central Ao Vivo", "Live Center Prediction Game"],
    ["Acerte os placares da 3ª rodada e dispute a viagem para a final. Participação gratuita, um palpite por partida, ranking atualizado em tempo real.", "Predict matchday 3 scores for a chance to win a trip to the final. Free entry, one prediction per match, with a real-time leaderboard."],
    ["Escolha o resultado", "Choose the result"],
    ["Palpite no vencedor e no placar exato de cada jogo da rodada até o apito inicial.", "Predict the winner and exact score of every match before kickoff."],
    ["Acompanhe ao vivo", "Follow live"],
    ["Seus pontos são recalculados a cada gol, junto com a tabela em tempo real desta página.", "Your points are recalculated after every goal alongside this page's real-time standings."],
    ["Resgate o prêmio", "Claim your prize"],
    ["O ranking fecha 30 minutos após o último jogo e os prêmios saem no mesmo dia.", "The leaderboard closes 30 minutes after the final match, and prizes are awarded the same day."],
    ["Passo", "Step"],
    ["Premiação", "Prizes"],
    ["Seu palpite", "Your prediction"],
    ["fecha em", "closes in"],
    ["Resultado final", "Final result"],
    ["Vitória", "Win for"],
    ["Placar exato (bônus de 5 pontos)", "Exact score (5-point bonus)"],
    ["Escolha um resultado antes de enviar o palpite.", "Choose a result before submitting your prediction."],
    ["Enviar palpite", "Submit prediction"],
    ["Palpite registrado", "Prediction submitted"],
    ["Editar palpite", "Edit prediction"],
    ["Participação gratuita · você pode editar até o apito inicial", "Free entry · you can edit until kickoff"],
    ["Promoção válida de 11 a 19 de junho, para maiores de 18 anos, sem necessidade de compra. Um palpite por CPF por partida. Consulte o regulamento completo e a política de privacidade antes de participar.", "Giveaway valid June 11–19 for participants aged 18 or over; no purchase necessary. One prediction per verified participant per match. Review the full rules and privacy policy before entering."],
    ["Você receberá uma notificação quando o ranking for atualizado. Enquanto o jogo rola, acompanhe a tabela ao vivo nesta página.", "You will be notified when the leaderboard updates. While the match is live, follow the standings on this page."],
    ["Diminuir gols de", "Decrease goals for"],
    ["Aumentar gols de", "Increase goals for"],
    ["Gols de", "Goals for"],
    ["palpites", "predictions"],

    ["Nesta página", "On this page"],
    ["Condições em tempo real", "Real-time conditions"],
    ["Reprodução dos lances", "Highlight replays"],
    ["Bolão e premiação", "Prediction game and prizes"],
    ["Acessibilidade", "Accessibility"],
    ["Navegação completa por teclado, com foco sempre visível.", "Full keyboard navigation with focus always visible."],
    ["Estados de partida sinalizados por ícone e texto, não apenas por cor.", "Match states are communicated by icon and text, not color alone."],
    ["Animações reduzidas automaticamente quando o sistema pede menos movimento.", "Motion is reduced automatically when the system requests less movement."],
    ["Atualizações importantes anunciadas para leitores de tela.", "Important updates are announced to screen readers."],
    ["Tabela em tempo real, condições de jogo e reprodução tática dos melhores lances da rodada. Feed atualizado a cada 3 segundos, com controle manual de pausa para quem prefere ler sem movimento.", "Real-time standings, match conditions, and tactical replays of the round's best plays. The feed updates every three seconds, with manual pause control for readers who prefer a still interface."],
    ["Projeto de demonstração: placares, estatísticas e lances são simulados e não representam partidas reais. Nenhum dado pessoal é coletado nesta página.", "Demonstration project: scores, statistics, and highlights are simulated and do not represent real matches. No personal data is collected on this page."],
    ["Conteúdo demonstrativo", "Demonstration content"],
    ["Fuso horário exibido", "Displayed time zone"],

    ["França", "France"], ["Países Baixos", "Netherlands"], ["Espanha", "Spain"],
    ["Itália", "Italy"], ["Croácia", "Croatia"], ["Bélgica", "Belgium"],
    ["México", "Mexico"], ["Canadá", "Canada"], ["Japão", "Japan"],
    ["Coreia do Sul", "South Korea"], ["Austrália", "Australia"], ["Brasil", "Brazil"],
    ["Cidade do México", "Mexico City"], ["Nova Jersey", "New Jersey"], ["São Francisco", "San Francisco"],
    ["Grupo", "Group"], ["rodada", "matchday"], ["3ª", "3rd"],
    ["INT", "HT"], ["FIM", "FT"],

    ["Condições", "Conditions"],
    ["Entrar no bolão", "Enter the prediction game"],
    ["decisão de vaga", "qualification decider"],
    ["LINHA DO TEMPO", "TIMELINE"],
    ["NARRAÇÃO EM TEMPO REAL", "LIVE COMMENTARY"],
    ["NARRAÇÃO IN REAL TIME", "LIVE COMMENTARY"],
    ["Entra Garnacho, sai Nico González", "Garnacho on, Nico González off"],
    ["Defesaça do goleiro", "Spectacular goalkeeper save"],
    ["Saveça do goleiro", "Spectacular goalkeeper save"],
    ["Defesaça", "Spectacular save"],
    ["Saveça", "Spectacular save"],
    ["Reflexo no ângulo", "Reflex save into the top corner"],
    ["Chute de fora da área", "Shot from outside the box"],
    ["Falta tática no meio", "Tactical foul in midfield"],
    ["Foul tática no meio", "Tactical foul in midfield"],
    ["Assistência de Messi", "Messi assist"],
    ["Bola rolando no Azteca", "Play underway at the Azteca"],
    ["Árbitro", "Referee"],
    ["Câmera", "Camera"],
    ["OUTROS JOGOS DA RODADA", "OTHER MATCHES THIS MATCHDAY"],
    ["OUTROS JOGOS DA MATCHDAY", "OTHER MATCHES THIS MATCHDAY"],
    ["Estado de cada partida com ícone e texto — nunca só por cor", "Every match state uses an icon and text — never color alone"],
    ["sincronizada há", "synced"],
    ["jogo(s) influenciando esta chave", "match(es) affecting this group"],
    ["posição mantida", "position unchanged"],
    ["LEGENDA DAS ZONAS", "ZONE LEGEND"],
    ["ABREVIAÇÕES", "ABBREVIATIONS"],
    ["Critérios de desempate na ordem: pontos, saldo de gols, gols pró e ranking FIFA. Clique em qualquer cabeçalho para reordenar — a coluna Pos sempre mostra a posição oficial da chave.", "Tiebreakers in order: points, goal difference, goals scored, and FIFA ranking. Select any heading to reorder — the Pos column always shows the group's official position."],
    ["Critérios de desdraw na ordem: points, goal difference, goals for e ranking FIFA. Clique em qualquer cabeçalho para reordenar — a coluna Pos sempre mostra a posição oficial da chave.", "Tiebreakers in order: points, goal difference, goals scored, and FIFA ranking. Select any heading to reorder — the Pos column always shows the group's official position."],
    ["Na visão Ao vivo (parcial), jogos em andamento entram como resultado provisório e as linhas piscam quando mudam. Use Confirmada para ver apenas as duas primeiras rodadas.", "In Live (provisional) view, active matches count as provisional results and changed rows flash. Use Confirmed to show only the first two matchdays."],
    ["Na visão Live (provisional), jogos em andamento entram como resultado provisório e as rows piscam quando mudam. Use Confirmed para ver apenas as duas primeiras matchdays.", "In Live (provisional) view, active matches count as provisional results and changed rows flash. Use Confirmed to show only the first two matchdays."],
    ["sensação", "feels like"],
    ["irrigação às", "irrigated at"],
    ["PÚBLICO PRESENTE", "ATTENDANCE"],
    ["da capacidade", "of capacity"],
    ["da capacity", "of capacity"],
    ["Sem revisões em andamento", "No reviews in progress"],
    ["Cabine", "Booth"],
    ["comunicação aberta com o campo", "open communication with pitchside officials"],
    ["PRESSÃO E DISPUTA", "PRESSURE AND CONTESTS"],
    ["últimos 4 min", "last 4 min"],
    ["DISTÂNCIA PERCORRIDA", "DISTANCE COVERED"],
    ["lance(s) exibido(s)", "highlight(s) displayed"],
    ["lance(s) displayed", "highlight(s) displayed"],
    ["visualizações", "views"],

    ["Voleio acrobático de Álvarez", "Álvarez's acrobatic volley"],
    ["Cruzamento rasteiro da direita, ajuste de corpo em 0,4 s e voleio no ângulo. O lance de maior xG da rodada.", "A low cross from the right, a body adjustment in 0.4 seconds, and a volley into the top corner. The matchday's highest-xG play."],
    ["Cruzamento rasteiro da direita, ajuste de corpo em 0,4 s e voleio no ângulo. O lance de maior xG da matchday.", "A low cross from the right, a body adjustment in 0.4 seconds, and a volley into the top corner. The matchday's highest-xG play."],
    ["Contra-ataque de 9 segundos", "Nine-second counterattack"],
    ["Counterattack de 9 segundos", "Nine-second counterattack"],
    ["Do próprio campo ao gol em nove segundos, com três passes verticais e nenhum toque para trás.", "From their own half to goal in nine seconds, with three vertical passes and no backward touch."],
    ["Transição", "Transition"],
    ["Defesa dupla de Ramsdale", "Ramsdale's double save"],
    ["Duas defesas em 1,2 s: a primeira com o pé direito, a segunda com a ponta dos dedos na saída do rebote.", "Two saves in 1.2 seconds: the first with his right foot, the second with his fingertips on the rebound."],
    ["Falta no ângulo de Pedri", "Pedri's top-corner free kick"],
    ["Foul no ângulo de Pedri", "Pedri's top-corner free kick"],
    ["Barreira de cinco, curva de 2,1 m e bola no ângulo direito. Nenhum toque antes do gol.", "A five-man wall, 2.1 meters of curl, and the ball into the right top corner. No touch before the goal."],
    ["Drible triplo na linha de fundo", "Triple dribble on the byline"],
    ["Três marcadores em cinco metros de linha de fundo e assistência de calcanhar para a área.", "Three defenders beaten within five meters of the byline, followed by a backheel assist into the box."],
    ["Lançamento de 58 metros", "58-meter pass"],
    ["Passe de primeira do campo de defesa direto no pé do atacante em movimento, sem quique.", "A first-time pass from the defensive half straight to the moving attacker's foot, without a bounce."],
    ["Pass de primeira do campo de defesa direto no pé do atacante em movimento, sem quique.", "A first-time pass from the defensive half straight to the moving attacker's foot, without a bounce."],
    ["Cada reprodução é um diagrama tático animado, gerado a partir dos dados de rastreamento do lance — abre em janela própria, com capítulos, velocidade ajustável e navegação por teclado.", "Every replay is an animated tactical diagram generated from play-tracking data. It opens in its own window with chapters, adjustable speed, and keyboard navigation."],

    ["PROMOÇÃO DA COPA", "WORLD CUP GIVEAWAY"],
    ["GIVEAWAY DA WORLD CUP", "WORLD CUP GIVEAWAY"],
    ["Viagem para a final + 2 ingressos categoria 1", "Trip to the final + two Category 1 tickets"],
    ["Aéreo, hospedagem 4 noites e transfer inclusos", "Flights, four hotel nights, and transfers included"],
    ["Pacote de créditos na loja", "Store credit package"],
    ["Empate", "Draw"],
    ["Derrota", "Loss"],
    ["há", "ago"],

    ["Ordenar por", "Sort by"],
    ["parcial, jogo em andamento", "provisional, match in progress"],
    ["Ocupação:", "Occupancy:"],
    ["Gráfico de pressão: valores acima da linha central indicam domínio de", "Pressure chart: values above the center line indicate control by"],
    ["abaixo indicam domínio de", "values below indicate control by"],
    ["Temperatura do jogo:", "Match temperature:"],
    ["aos", "in the"],
    ["minutos", "minutes"],
    ["duração", "duration"],
    ["contra", "versus"],
    ["posição(ões)", "position(s)"],
    ["posições ganhas", "positions gained"],
    ["posições perdidas", "positions lost"],
    ["Standings do Group E, atualizada in real time. Official group order.", "Group E standings, updated in real time. Official group order."],
    ["Critérios de desdraw na ordem: pontos, saldo de gols, gols pró e ranking FIFA. Clique em qualquer cabeçalho para reordenar — a coluna Pos sempre mostra a posição oficial da chave.", "Tiebreakers in order: points, goal difference, goals scored, and FIFA ranking. Select any heading to reorder — the Pos column always shows the group's official position."]
  ].sort((a, b) => b[0].length - a[0].length);

  const phraseMap = new Map(phrases);
  const pattern = new RegExp(phrases.map(([source]) => source.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|"), "g");
  const translate = (value) => {
    let current = value;
    for (let pass = 0; pass < 4; pass += 1) {
      const next = current.replace(pattern, (source) => phraseMap.get(source) || source);
      if (next === current) break;
      current = next;
    }
    return current
      .replace(/\bago\s+(\d+s)\b/g, "$1 ago")
      .replace(/\b(\d+)\s+a\s+(\d+)\b/g, "$1–$2")
      .replace(/\bin the (\d+) minutes\b/g, "in minute $1");
  };
  window.__translateVisibleText = translate;
  const selfUpdated = new WeakSet();

  const translateNode = (root) => {
    if (root.nodeType === Node.TEXT_NODE) {
      const next = translate(root.nodeValue || "");
      if (next !== root.nodeValue) {
        selfUpdated.add(root);
        root.nodeValue = next;
      }
      return;
    }
    if (root.nodeType !== Node.ELEMENT_NODE && root.nodeType !== Node.DOCUMENT_NODE) return;
    const element = root.nodeType === Node.ELEMENT_NODE ? root : null;
    const translatedAttributes = ["aria-label", "title", "placeholder", "data-match"];
    const translateElementAttributes = (target) => {
      for (const attribute of translatedAttributes) {
        if (!target.hasAttribute(attribute)) continue;
        const value = target.getAttribute(attribute) || "";
        const next = translate(value);
        if (next !== value) target.setAttribute(attribute, next);
      }
    };
    if (element) {
      translateElementAttributes(element);
      for (const descendant of element.querySelectorAll("[aria-label],[title],[placeholder],[data-match]")) {
        translateElementAttributes(descendant);
      }
    }
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    let node;
    while ((node = walker.nextNode())) {
      if (node.parentElement?.matches("script, style, noscript")) continue;
      const next = translate(node.nodeValue || "");
      if (next !== node.nodeValue) {
        selfUpdated.add(node);
        node.nodeValue = next;
      }
    }
  };

  translateNode(document);

  // React commits many nested nodes in one burst. Translate the settled DOM once
  // per animation frame instead of rescanning every added subtree separately.
  let scheduled = false;
  const scheduleTranslation = () => {
    if (scheduled) return;
    scheduled = true;
    requestAnimationFrame(() => {
      scheduled = false;
      translateNode(document.body || document.documentElement);
    });
  };
  new MutationObserver((records) => {
    let needsTranslation = false;
    for (const record of records) {
      if (record.type === "characterData" && selfUpdated.has(record.target)) {
        selfUpdated.delete(record.target);
        continue;
      }
      needsTranslation = true;
    }
    if (needsTranslation) scheduleTranslation();
  }).observe(document.documentElement, { childList: true, subtree: true, characterData: true });
  window.setInterval(scheduleTranslation, 1000);
})();
