(() => {
  "use strict";

  document.documentElement.lang = "en";
  document.title = "World Cup 2026 · Live Center — Scores, Standings, and Highlights";

  const phrases = [
    ["Esta é uma página de demonstração: placares, tabelas, artilharia e replays são gerados por um simulador em tempo real que roda no seu navegador, sem relação com a FIFA ou com os detentores dos direitos de transmissão. Para produção, conecte a central a um provedor oficial de dados esportivos e substitua o simulador pelo streaming de eventos.", "This is a demonstration page: scores, standings, top-scorer rankings, and replays are generated by a real-time simulator running in your browser. It is not affiliated with FIFA or any broadcast-rights holder. For production use, connect the center to an official sports-data provider and replace the simulator with an event stream."],
    ["Os 2 primeiros de cada grupo avançam direto; os 8 melhores terceiros completam os 32 classificados. Critérios de desempate: pontos, saldo de gols, gols pró e confronto direto.", "The top two teams in each group advance directly; the eight best third-place teams complete the round of 32. Tiebreakers: points, goal difference, goals scored, and head-to-head record."],
    ["Cada lance é reconstruído com a trajetória real da bola e a movimentação dos marcadores. Assista em velocidade normal ou em câmera lenta, quantas vezes quiser.", "Every play is reconstructed with the ball's trajectory and the defenders' movement. Watch at normal speed or in slow motion as many times as you like."],
    ["Placar minuto a minuto, tabela de pontos que se recalcula a cada gol, replays em animação tática dos melhores momentos e o maior bolão do país — tudo de graça, sem instalar nada.", "Minute-by-minute scores, standings recalculated after every goal, animated tactical highlight replays, and the country's biggest prediction contest — all free, with nothing to install."],
    ["Placar, cronômetro, timeline de lances, clima do estádio e estatísticas avançadas atualizados automaticamente a cada poucos segundos — sem recarregar a página.", "Scores, match clocks, event timelines, stadium weather, and advanced statistics update automatically every few seconds — no page reload required."],
    ["Dica: ative o 🔔 em qualquer partida da central para receber alerta de gol na tela — funciona mesmo com a aba em segundo plano (as atualizações pausam para poupar bateria e retomam ao voltar).", "Tip: activate the 🔔 on any match to receive on-screen goal alerts — it even works while the tab is in the background (updates pause to save battery and resume when you return)."],
    ["A chuteira de ouro muda de dono em tempo real: cada gol registrado na central entra automaticamente nesta lista e no radar de lances de todos os jogos.", "The Golden Boot race changes in real time: every goal registered by the center automatically enters this list and the event radar for every match."],
    ["Palpite no placar do próximo jogo e no campeão. A cada rodada você ganha pontos automaticamente — quem mais acertar leva o prêmio no Pix.", "Predict the next match score and the champion. You earn points automatically each round — the most accurate player wins the cash prize via Pix."],
    ["Detectamos Asia/Shanghai e convertemos automaticamente os 104 jogos — nada de calcular “menos 4 horas”.", "We detected Asia/Shanghai and automatically converted all 104 matches — no need to calculate time differences yourself."],
    ["Navegação por teclado nas abas e grupos, contraste AA, leitores de tela avisados a cada gol.", "Keyboard navigation for tabs and groups, AA contrast, and screen-reader announcements for every goal."],
    ["Acompanhe os 104 jogos da Copa de 2026 com placar em tempo real, tabelas que se atualizam sozinhas e replays animados de cada lance decisivo.", "Follow all 104 matches of the 2026 World Cup with real-time scores, self-updating standings, and animated replays of every decisive play."],
    ["Toque em uma sede para ver capacidade, fuso horário e quantas partidas do torneio passam por lá — útil para planejar de que horário você vai assistir.", "Select a host city to see capacity, time zone, and how many tournament matches it hosts — useful for planning when to watch."],
    ["Ao trocar de aba, as atualizações pausam sozinhas e retomam do ponto exato quando você volta.", "When you switch tabs, updates pause automatically and resume from the exact point where they stopped when you return."],
    ["A tabela mostra os critérios aplicados e o ranking dos melhores terceiros, sem caixa-preta.", "The table shows the applied criteria and the ranking of the best third-place teams, with no black box."],
    ["Premiação liberada em até 48h após a final, direto na sua chave Pix.", "Prizes are released within 48 hours of the final, directly to your Pix account."],
    ["Escolha o placar do próximo jogo e o campeão. Sem cadastro longo, sem cartão.", "Choose the next match score and the champion. No lengthy registration and no card required."],
    ["Os detalhes que costumam faltar em página de promoção — e que aqui fazem parte do produto.", "The details that promotional pages usually omit — built into the product here."],
    ["Cada lance pode ser reproduzido quantas vezes quiser, em 1× ou 0,5×, com a trajetória da bola.", "Replay every play as many times as you like at 1× or 0.5× speed, with the ball trajectory shown."],
    ["Ative o sininho em qualquer partida e receba o aviso na tela, com autor e minuto do gol.", "Activate the bell on any match to receive an on-screen alert showing the scorer and goal time."],
    ["Corta para o meio, abre o pé e a bola descreve uma curva que morre no ângulo esquerdo. 3 defensores batidos em 4 segundos.", "He cuts inside, opens his body, and curls the ball into the upper-left corner. Three defenders beaten in four seconds."],
    ["Cruzamento rasteiro rebatido pela zaga, ele acerta o meio da bola sem deixar cair: 112 km/h no ângulo.", "A low cross is cleared by the defense, and he strikes the ball before it drops: 112 km/h into the top corner."],
    ["Roubada no campo de defesa, 36,2 km/h de velocidade máxima e finalização entre as pernas do goleiro.", "The ball is won in defense, the runner reaches 36.2 km/h, and finishes through the goalkeeper's legs."],
    ["Três toques do escanteio defendido ao gol: tabela de primeira, inversão e finalização de placa.", "Three touches from a defended corner to the goal: a one-touch combination, a switch of play, and a spectacular finish."],
    ["Já caído para um lado, ele reage e espalma com a ponta dos dedos no acréscimo final.", "Already falling one way, he reacts and tips the ball away with his fingertips in stoppage time."],
    ["27 metros, pé direito, sem rotação. A bola cai como pedra depois de passar por cima da barreira.", "Twenty-seven meters, right foot, no spin. The ball drops like a stone after clearing the wall."],
    ["Metrô e trem gratuitos com ingresso do dia em 9 das 12 sedes.", "Free metro and train travel with a same-day ticket in nine of the twelve host cities."],
    ["ESTA para os EUA e eTA para o Canadá saem em até 72h para brasileiros.", "ESTA for the United States and eTA for Canada are issued to Brazilian travelers within 72 hours."],
    ["Sorteio de lotes extras a cada rodada no app oficial da FIFA.", "Extra ticket batches are drawn after every round in the official FIFA app."],
    ["Wi-Fi liberado em todos os estádios para acompanhar a central ao vivo.", "Free Wi-Fi is available in every stadium so fans can follow the live center."],
    ["Sua pontuação sobe automaticamente conforme os gols acontecem na central.", "Your score rises automatically as goals are registered by the live center."],
    ["Usamos só para avisar do prêmio. Nada de spam — você pode sair com 1 clique.", "We only use it to notify you about prizes. No spam — unsubscribe in one click."],
    ["🍪 Usamos cookies para manter seu grupo favorito, seus alertas de gol e medir audiência. Você escolhe o que aceitar.", "🍪 We use cookies to remember your favorite group and goal alerts and to measure audience activity. You choose what to accept."],
    ["+ viagem para a final em Nova Jersey", "+ trip to the final in New Jersey"],
    ["+ camisa oficial autografada", "+ signed official jersey"],
    ["+18 · jogue com responsabilidade", "18+ · play responsibly"],
    ["Participação gratuita · Sem cartão de crédito · Jogue com responsabilidade", "Free entry · No credit card · Play responsibly"],
    ["Dados tratados conforme a LGPD", "Data processed in accordance with Brazil's LGPD"],
    ["Acessibilidade AA · navegação por teclado", "AA accessibility · keyboard navigation"],
    ["Acessível de verdade", "Truly accessible"],
    ["Alerta de gol sem instalar app", "Goal alerts without installing an app"],
    ["Modo economia inteligente", "Smart power-saving mode"],
    ["Desempate transparente", "Transparent tiebreakers"],
    ["Horários no seu fuso", "Times in your time zone"],
    ["Nossas fontes de dados", "Our data sources"],
    ["Demonstração com dados simulados", "Demonstration with simulated data"],
    ["checagem cruzada antes de publicar", "cross-checked before publication"],
    ["com fallback automático em polling", "with automatic polling fallback"],
    ["monitorada em 4 regiões", "monitored across four regions"],
    ["3 provedores", "3 providers"],
    ["5 ciclos de atualização nesta sessão", "5 update cycles this session"],
    ["Latência média", "Average latency"],
    ["Disponibilidade", "Availability"],
    ["Conexão", "Connection"],
    ["Atualização", "Update"],
    ["Tempo real ativo", "Live updates active"],
    ["Somar jogos em andamento", "Include matches in progress"],
    ["Placar minuto a minuto", "Minute-by-minute scores"],
    ["Classificação atualizada do grupo D", "Updated Group D standings"],
    ["Ranking dos melhores terceiros", "Best third-place teams"],
    ["Os 8 primeiros desta lista completam a fase eliminatória de 32 seleções.", "The top eight teams on this list complete the 32-team knockout stage."],
    ["2 primeiros avançam", "Top 2 advance"],
    ["3º na repescagem", "3rd enters the playoff"],
    ["2ª rodada", "Round 2"],
    ["1º lugar", "1st place"],
    ["2º lugar", "2nd place"],
    ["3º ao 10º", "3rd–10th"],
    ["11º ao 500º", "11th–500th"],
    ["1º tempo", "1st half"],
    ["2º tempo", "2nd half"],
    ["Próxima partida começa em", "Next match starts in"],
    ["Próximo jogo · Hoje", "Next match · Today"],
    ["Jogo em destaque", "Featured match"],
    ["Placar minuto a minuto", "Minute-by-minute score"],
    ["Ver lances e estatísticas", "View highlights and statistics"],
    ["Estado das partidas", "Match status"],
    ["Partidas aqui", "Matches here"],
    ["FIM", "FT"],
    ["intervalo", "half-time"],
    ["casa", "home"],
    ["visitante", "away"],
    ["Falta tática", "Tactical foul"],
    ["Reclamação com a arbitragem", "Appeal to the referee"],
    ["Gol anulado por impedimento", "Goal disallowed for offside"],
    ["Pênalti convertido", "Penalty scored"],
    ["Assistência", "Assist"],
    ["Drible", "Dribble"],
    ["Falta", "Foul"],
    ["Radar de lances", "Event radar"],
    ["radar de lances", "event radar"],
    ["minuto a minuto", "minute by minute"],
    ["replay tático animado", "animated tactical replay"],
    ["recalculada a cada gol", "recalculated after every goal"],
    ["atualizado a cada gol", "updated after every goal"],
    ["Melhores momentos", "Highlights"],
    ["Curva impossível no ângulo", "Impossible curler into the top corner"],
    ["Voleio de primeira na entrada da área", "First-time volley from the edge of the box"],
    ["Arrancada de 70 metros", "70-meter solo run"],
    ["Contra-ataque em 9 segundos", "Nine-second counterattack"],
    ["Falta com barreira congelada", "Free kick over a frozen wall"],
    ["Defesa milagrosa no último lance", "Miraculous save on the final play"],
    ["Replay em câmera lenta", "Slow-motion replay"],
    ["Gols no torneio", "Tournament goals"],
    ["Média por jogo", "Average per match"],
    ["Média de gols", "Goals per match"],
    ["Chuteira de Ouro", "Golden Boot"],
    ["Artilharia", "Top scorers"],
    ["Torcedores online", "Fans online"],
    ["Gols, tabelas e o melhor lance do dia. Cancele quando quiser.", "Goals, standings, and the play of the day. Cancel anytime."],
    ["Resumo diário no seu e-mail", "Daily recap by email"],
    ["Assinar", "Subscribe"],
    ["Como pontuar", "How scoring works"],
    ["Palpite em 1 minuto", "Predict in one minute"],
    ["Receba via Pix", "Receive your prize via Pix"],
    ["Prêmios e pagamento", "Prizes and payment"],
    ["Prêmio do bolão", "Prediction-contest prize"],
    ["Entrar no bolão", "Enter the prediction contest"],
    ["Palpitar e concorrer a R$ 500 mil", "Make a prediction for a chance to win R$500,000"],
    ["Confirmar palpite e concorrer", "Confirm prediction and enter"],
    ["Seu palpite", "Your prediction"],
    ["Nome completo", "Full name"],
    ["E-mail ou WhatsApp", "Email or WhatsApp"],
    ["Selecione uma seleção…", "Select a team…"],
    ["Como no seu documento", "As shown on your ID"],
    ["Só essenciais", "Essential only"],
    ["Aceitar todos", "Accept all"],
    ["Preferências", "Preferences"],
    ["Dúvidas frequentes", "Frequently asked questions"],
    ["Regulamento completo", "Full rules"],
    ["regulamento", "rules"],
    ["Institucional", "Company"],
    ["Quem somos", "About us"],
    ["Trabalhe com a gente", "Careers"],
    ["Imprensa", "Press"],
    ["Contato", "Contact"],
    ["Sedes e fusos", "Host cities and time zones"],
    ["Sedes", "Host cities"],
    ["Ingressos", "Tickets"],
    ["Vistos", "Visas"],
    ["Transporte", "Transportation"],
    ["Capacidade", "Capacity"],
    ["Gramado", "Pitch"],
    ["Híbrido", "Hybrid"],
    ["Vagas preenchidas", "Places filled"],
    ["cada, via Pix imediato", "each, paid instantly via Pix"],
    ["em crédito de streaming", "in streaming credit"],
    ["com o celular na mão", "with a phone in hand"],
    ["do gol no estádio até o seu placar", "from a stadium goal to your scoreboard"],
    ["1 fuso de cada vez", "one time zone at a time"],
    ["Pular para a central ao vivo", "Skip to the live center"],
    ["Acompanhe ao vivo", "Follow live"],
    ["Central ao vivo", "Live center"],
    ["CENTRAL COPA", "WORLD CUP CENTER"],
    ["EM TEMPO REAL", "IN REAL TIME"],
    ["NA SUA TELA", "ON YOUR SCREEN"],
    ["2026 · AO VIVO", "2026 · LIVE"],
    ["Ao vivo agora", "Live now"],
    ["Ao vivo", "Live"],
    ["Todos", "All"],
    ["Últimos", "Latest"],
    ["Tabela dos 12 grupos", "Standings for all 12 groups"],
    ["Ranking geral", "Overall ranking"],
    ["Grupos", "Groups"],
    ["Grupo", "Group"],
    ["Seleção", "Team"],
    ["Partidas", "Matches"],
    ["Jogos", "Matches"],
    ["Condições", "Conditions"],
    ["Estatísticas", "Statistics"],
    ["Finalizações", "Shots"],
    ["No alvo", "On target"],
    ["Fechar detalhes", "Close details"],
    ["Detalhes da partida", "Match details"],
    ["Abrir menu", "Open menu"],
    ["Compartilhar placar", "Share score"],
    ["Receber alerta de gol desta partida", "Receive goal alerts for this match"],
    ["Pausar atualizações em tempo real", "Pause live updates"],
    ["Vitória", "Win"],
    ["Empate", "Draw"],
    ["Derrota", "Loss"],
    ["Gols de ", "Goals by "],
    ["Assistir replay: ", "Watch replay: "],
    ["Hoje", "Today"],
    ["lugares", "seats"],
    ["partidas", "matches"],
    ["torcedores", "fans"],
    ["dias", "days"],
    ["horas", "hours"],
    ["seg", "sec"],
    ["min", "min"],
    ["pontos", "points"],
    ["cartões", "cards"],
    ["ter, 01 de set.", "Tue, Sep 1"],
    [" de 90+", " of 90+"],
    [" · ao vivo", " · live"],
    [" · 2º tempo", " · 2nd half"],
    ["Sol forte", "Bright sunshine"],
    ["Parcialmente nublado", "Partly cloudy"],
    ["Chuva leve", "Light rain"],
    ["Úmido e abafado", "Humid and muggy"],
    ["Política de privacidade", "Privacy Policy"],
    ["Termos de uso", "Terms of Use"],
    ["Regulamento da promoção", "Giveaway Rules"]
    ,["ciclos de atualização nesta sessão", "update cycles this session"]
    ,["Campeão do mundo", "World champion"]
    ,["Campeão", "Champion"]
    ,["Bolão", "Prediction contest"]
    ,["Finalização de fora da área", "Shot from outside the box"]
    ,["Fontes", "Sources"]
    ,["Fuso", "Time zone"]
    ,["Próximo jogo", "Next match"]
    ,["atualizada", "updated"]
    ,["atualizado", "updated"]
    ,["do grupo", "for Group"]
    ,["rodada", "round"]
    ,["jogos", "matches"]
    ,["jogo", "match"]
    ,["de pênalti", "from a penalty"]
    ,["grátis", "free"]
    ,["gols", "goals"]
    ,["Gols", "Goals"]
    ,["Costa do Marfim", "Ivory Coast"]
    ,["África do Sul", "South Africa"]
    ,["Áustria", "Austria"]
    ,["Argélia", "Algeria"]
    ,["Arábia Saudita", "Saudi Arabia"]
    ,["Cabo Verde", "Cape Verde"]
    ,["Catar", "Qatar"]
    ,["Irã", "Iran"]
    ,["Jordânia", "Jordan"]
    ,["Panamá", "Panama"]
    ,["Senegal", "Senegal"]
    ,["Tunísia", "Tunisia"]
    ,["Turquia", "Türkiye"]
    ,["Uzbequistão", "Uzbekistan"]
    ,["Como no seu documento", "As shown on your ID"]
    ,["seu@email.com", "you@example.com"]
    ,["voce@email.com ou (11) 90000-0000", "you@example.com or +1 555 0100"]
    ,["Próximas", "Upcoming"]
    ,["Encerradas", "Finished"]
    ,["Estádio Akron", "Akron Stadium"]
    ,["87.412 de 100.000", "87,412 of 100,000"]
    ,["18,7 mi", "18.7M"]
    ,["15,1 mi", "15.1M"]
    ,["12,4 mi", "12.4M"]
    ,["11,2 mi", "11.2M"]
    ,["9,8 mi", "9.8M"]
    ,["7,3 mi", "7.3M"]
    ,["2,4 mi", "2.4M"]
    ,["1,2 s", "1.2 sec"]
    ,["Curva de fora da área", "Curl from outside the box"]
    ,["Distância do gol", "Distance from goal"]
    ,["Probabilidade de gol", "Goal probability"]
    ,["Velocidade da bola", "Ball speed"]
    ,["Reproduzir de novo", "Play again"]
    ,["Reproduzir", "Play"]
    ,["Pausar", "Pause"]
    ,["GOOOL DO ", "GOAL FOR "]
    ,["GOOOL DA ", "GOAL FOR "]
    ,["GOL DO ", "GOAL FOR "]
    ,["GOL DA ", "GOAL FOR "]
    ,["JAPÃO", "JAPAN"]
    ,["do 2nd half", "of the 2nd half"]
    ,["Digite seu nome completo (mínimo 3 letras).", "Enter your full name (at least 3 characters)."]
    ,["Escolha a seleção que você acha que levanta a taça.", "Choose the team you think will lift the trophy."]
    ,["Informe um placar válido", "Enter a valid score"]
    ,["0 a 20", "0 to 20"]
    ,["para cada lado", "for each side"]
    ,["Use um e-mail válido ou um WhatsApp com DDD.", "Enter a valid email address or a WhatsApp number with area code."]
    ,["É necessário aceitar o rules para participar.", "You must accept the rules to enter."]
    ,["É necessário aceitar o regulamento para participar.", "You must accept the rules to enter."]
    ,[" de ", " of "]
    ,[" do ", " of the "]
    ,["atualizada do grupo", "for Group"]
    ,["grupo", "group"]
    ,["A COPA INTEIRA", "THE ENTIRE WORLD CUP"]
    ,["COPA", "WORLD CUP"]
    ,["INTEIRA", "ENTIRE"]
    ,["JOGOS", "MATCHES"]
    ,["SELEÇÕES", "TEAMS"]
    ,["seleções", "teams"]
    ,["jun", "Jun"]
    ,["jul", "Jul"]
    ,["2,00", "2.00"]
    ,["e o tratamento dos meus dados conforme a LGPD.", "and the processing of my data under Brazil's LGPD."]
    ,["12 estádios, 3 países", "12 stadiums, 3 countries"]
    ,["Classificado às oitavas", "Qualified for the round of 16"]
    ,["Nova Zelândia", "New Zealand"]
    ,["Zelândia", "Zealand"]
    ,["Números of the torneio", "Tournament by the numbers"]
    ,["Números do torneio", "Tournament by the numbers"]
    ,["Números", "Numbers"]
    ,["torneio", "tournament"]
    ,["em prêmios", "in prizes"]
    ,["pênalti", "penalty"]
    ,["⏳ Apostas para a próxima round encerram em", "⏳ Predictions for the next round close in"]
    ,["Apostas", "Predictions"]
    ,["próxima", "next"]
    ,["encerram", "close"]
    ,["estádios", "stadiums"]
    ,["países", "countries"]
    ,["Pensado para quem assiste", "Designed for the way you watch"]
    ,["Ver live center", "View live center"]
  ].sort((a, b) => b[0].length - a[0].length);

  const phraseMap = new Map(phrases);
  const escapeRegExp = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pattern = new RegExp(phrases.map(([source]) => escapeRegExp(source)).join("|"), "g");
  const translate = (value) => value
    .replace(pattern, (source) => phraseMap.get(source) || source)
    .replace(/\bupdated há (\d+)s\b/g, "updated $1s ago")
    .replace(/\b1 update cycles\b/g, "1 update cycle")
    .replace(/\b(\d{2,3})\.(\d{3}) seats\b/g, "$1,$2 seats")
    .replace(/\b(\d{2,3})\.(\d{3})\b/g, "$1,$2")
    .replace(/\b87\.412 de 100\.000\b/g, "87,412 of 100,000");
  const selfUpdated = new WeakSet();

  const translateNode = (root) => {
    if (root.nodeType === Node.TEXT_NODE) {
      const next = translate(root.nodeValue || "");
      if (next !== root.nodeValue) {
        selfUpdated.add(root);
        root.nodeValue = next;
      }
      return;
    }
    if (root.nodeType !== Node.ELEMENT_NODE && root.nodeType !== Node.DOCUMENT_NODE) return;
    const element = root.nodeType === Node.ELEMENT_NODE ? root : null;
    const elements = element ? [element, ...element.querySelectorAll("*")] : [...document.querySelectorAll("*")];
    for (const target of elements) {
      for (const attribute of ["aria-label", "title", "placeholder", "alt"]) {
        if (!target.hasAttribute(attribute)) continue;
        const value = target.getAttribute(attribute) || "";
        const next = translate(value);
        if (next !== value) target.setAttribute(attribute, next);
      }
    }
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    let node;
    while ((node = walker.nextNode())) {
      if (node.parentElement?.matches("script, style, noscript")) continue;
      const next = translate(node.nodeValue || "");
      if (next !== node.nodeValue) {
        selfUpdated.add(node);
        node.nodeValue = next;
      }
    }
  };

  translateNode(document);
  new MutationObserver((records) => {
    for (const record of records) {
      if (record.type === "characterData") {
        if (selfUpdated.has(record.target)) selfUpdated.delete(record.target);
        else translateNode(record.target);
      }
      for (const node of record.addedNodes) translateNode(node);
    }
  }).observe(document.documentElement, {
    childList: true,
    subtree: true,
    characterData: true
  });
})();
